sudo: false
language: node_js
node_js:
  - '8'
  - '10'
before_install:
  - 'wget http://mirrors.advancedhosters.com/apache/zookeeper/zookeeper-3.4.13/zookeeper-3.4.13.tar.gz'
  - 'tar xf zookeeper-3.4.13.tar.gz'
  - 'mv zookeeper-3.4.13/conf/zoo_sample.cfg zookeeper-3.4.13/conf/zoo.cfg'
  - './zookeeper-3.4.13/bin/zkServer.sh start'
install:
  - npm i npminstall && npminstall --registry=https://registry.npm.taobao.org
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov